apiVersion: v1
kind: Service
metadata:
  name: c7n-mysql-nodeport
  namespace: c7n-system
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 30306
    targetPort: 3306
    nodePort: 30001
  selector:
    choerodon.io/release: c7n-mysql
