apiVersion: v1
kind: Service
metadata:
  name: c7n-register-nodeport
  namespace: c7n-system
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 30307
    targetPort: 8000
    nodePort: 30002
  selector:
    choerodon.io/release: choerodon-register

